#!/usr/bin/env python3
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
#
# Print the filename attribute of a <program> element by label from a
# rawprogram XML file generated by qcom-ptool.
#
# Usage:  get-rawprogram-filename.py <label> <rawprogram0.xml>
#
# Example:
#   $ python3 get-rawprogram-filename.py rootfs rawprogram0.xml
#   disk-ufs.img2

import sys
import defusedxml.ElementTree as ET

if len(sys.argv) != 3:
    print(f"Usage: {sys.argv[0]} <label> <rawprogram0.xml>", file=sys.stderr)
    print("none")
else:
    label, xml_file = sys.argv[1], sys.argv[2]

    root = ET.parse(xml_file).getroot()
    e = root.find(f".//program[@label='{label}']")
    if e is None:
        print("none")
    else:
        filename = e.get("filename")
        # Strip any leading ../ path components
        while filename.startswith("../"):
            filename = filename[3:]
        print(filename)
